### PR TITLE
Added a couple slash commands

### PR DESCRIPTION
**Pull request by selectthegang**
I have added a couple slash commands such as "selfentry, random, featured" because why tf not. Please let me know if you want anything added or changed.

### CODE REVIEW

**Comment by selectthegang** [comment]
brain damage lol

**Comment by mat-1** [comment]
Where's the code?

**Comment by selectthegang** [comment]
It's in 5581118

**Comment by selectthegang** [comment]
Do i need to make another commit/pr

**Comment by Codemonkey51** [comment]
Also @selectthegang changed all the `'`'s to `"`'s lol

**Comment by Codemonkey51** [comment]
> 
> 
> It's in [5581118](https://github.com/repldex/Repldex/commit/5581118afbfeea52e5e6e075106854bf568bbd63)

uhhhhh that commit isnt in the branch ur pr-ing into repldex ._.

**Comment by selectthegang** [comment]
Fuck, vscode messed with it

**Comment by selectthegang** [comment]
i will fix this

**Comment by Codemonkey51** [comment]
> 
> 
> It's in [5581118](https://github.com/repldex/Repldex/commit/5581118afbfeea52e5e6e075106854bf568bbd63)

that only console.logs the commands tho.... not actually handling them

**Comment by selectthegang** [comment]
> > It's in [5581118](https://github.com/repldex/Repldex/commit/5581118afbfeea52e5e6e075106854bf568bbd63)
> 
> that only console.logs the commands tho.... not actually handling them

You do know that i just added onto the code that Mat already had, there was nothing handling them

**Pull request closed without merging**
