### PR TITLE
Make commands better

### PR DESCRIPTION
**Pull request by mat-1**
The interaction when doing `handle` in bot.ts is now a lot easier to use, and it comes with TypeScript typings.

### CODE REVIEW

**Review by jetstream0 — APPROVED** [review]
looks good

**Comment by selectthegang** [comment]
I disapprove, you didn't add params to any of the functions

**Comment by mat-1** [comment]
> I disapprove, you didn't add params to any of the functions

Can you elaborate on this? Are you referring to a different unrelated part of the code?

**Comment by selectthegang** [comment]
> > I disapprove, you didn't add params to any of the functions
> 
> Can you elaborate on this? Are you referring to a different unrelated part of the code?

Each function that takes a value should have a comment added before the function that looks like
`/**
* @param String name - the entry name`
* Information about this function
*/`

**Comment by selectthegang** [comment]
Code Blocks suck

**Comment by jetstream0** [comment]
Select, this is not necessary as we are not going to auto generate docs (those are internal functions), and anyone can figure out the parameters by looking at them because this is typescript.

**Comment by selectthegang** [comment]
Yeah, but either way we should have params because it helps both Replit and VScode code intelligence. Mat has replied to my message on the Repldex Discord saying that he might add it (https://discord.com/channels/662039537479843850/662039537932959754/911839737650761769)

**Review by selectthegang — CHANGES_REQUESTED** [review]
Functions need params for code intelligence

**Review by selectthegang — APPROVED** [review]

**Review by selectthegang — APPROVED** [review]

**Review by selectthegang — APPROVED** [review]
idk why it isn't saying i approved

**Pull request merged**
