### PR TITLE
[BOT] bring more functionality to discord bot

### PR DESCRIPTION
**Pull request by jetstream0**

### CODE REVIEW

**Review by selectthegang — APPROVED** [review]
LGTM

**Review by selectthegang — APPROVED** [review]
Had to reapprove since new commit was made. Anyways, looks good to me

**Review by selectthegang — DISMISSED** [review]
[Final Review]
I have tested every single portion of this pr to ensure that everything is working as intended and no breaking changes occurred. This pr does work well 100%, but error handling will be needed very soon.

**Comment by jetstream0** [comment]
@mat-1 Please do a brief review if you have time

**Review by mat-1 — CHANGES_REQUESTED** [review]
Please run `npm run format` to automatically fix the styling issues and manually fix the syntax errors. You can do `npm run lint` to view them all. I'll do a real review after this is done since it's kinda hard to read the code right now.

**Review by selectthegang — CHANGES_REQUESTED** [review]
Please run `npm run format` to automatically fix the styling issues and to pass the tests

**Review by selectthegang — DISMISSED** [review]
Looks good to me, all tests have passed as needed!

**Review by selectthegang — CHANGES_REQUESTED** [review]
Please fix the conflicts!

**Comment by selectthegang** [comment]
This pr has been closed as needed to fix issues.

**Pull request closed without merging**
