### PR TITLE
Sort entries by when they were last edited

### PR DESCRIPTION
**Pull request by mat-1**
Adds the "editedAt" field and sorts by that by default.

### CODE REVIEW

**Review by selectthegang — APPROVED** [review]
It looks good to me, code ran good.

**Comment by selectthegang** [comment]
Fix conflicts, then i will merge ig

**Comment by selectthegang** [comment]
This pr has been opened for a long while, so am going to close as no updates have been placed.

**Comment by mat-1** [comment]
This is still ready for review.

**Comment by selectthegang** [comment]
Fix the conflicts, then i will be happy to review this. For now, i have placed the Ready for Review label to this pr

**Comment by selectthegang** [comment]
Reviewing this pr now

**Comment by selectthegang** [comment]
Changes approved, merging now

**Pull request merged**
