### PR TITLE
Entry visibility

### PR DESCRIPTION
**Pull request by mat-1**
Entries can now be in one of three "visibilities":
- Visible
    - Most entries will be in this state, since they are the ones that are most easily accessible.
    - Shown in entry list/search.
    - Can be accessed by anyone via /entry/[slug].
- Unlisted
    - This is meant for unverified or work-in-progress entries.
    - When an entry is initially created, it's set as unlisted.
    - Unlisted entries cannot be found by default through the entry list or search.
    - Can be accessed by anyone via /entry/[slug].
- Hidden
    - This is meant for entries that break the rules or where a relevant user requested that the entry be deleted.
    - Not shown in search.
    - Only accessible by admins with a direct link to /entry/[id].
    - This is similar to v2's unlisted feature, when old unlisted entries are migrated they will be made hidden.

The entry list gained a new setting, filtering by visibility. This is only shown for logged-in users. Logged-in users can choose to list all unlisted entries through this. Admins can list all *hidden* entries through this.

Admins can change the visibility of any entry, and they can set the visibility of their own entries when they are initially creating one.

## Screenshots
Entry list with the "visible" filter enabled.
The entry list on the index page. There's a set of toggle buttons labeled 'Filter' at the right, with the buttons being named 'visible', 'unlisted', and 'hidden'. Only the visible button is enabled.
Entry list with "visible" and "unlisted" enabled, showing an unlisted entry.
The entry list on the index page. The 'visible' and 'unlisted' filters are enabled, showing an unlisted entry. This unlisted entry has a little badge that says "unlisted".
Unlisted/hidden entries have a little badge thing to the right that says it's unlisted.
Unlisted entry showing an "unlisted" badge to the right
Admins can change the visibility of any entry through a dropdown.
A dropdown labeled 'Visibility', with the choices being visible, unlisted, and hidden

### CODE REVIEW

**Review by selectthegang — CHANGES_REQUESTED** [review]
Looks good, will approve this review once issue with Mobile design is fixed.

**Review by selectthegang — APPROVED** [review]
Looks good, approved this review. You may merge this pr as necessary

**Review by selectthegang — CHANGES_REQUESTED** [review]
The latest commit has brought a small design issue towards mobile devices. If you fix this issue and make the site more responsive for Mobile devices, i will approve this merge.

**Review by selectthegang — APPROVED** [review]

**Review by selectthegang — CHANGES_REQUESTED** [review]
Some mobile design issues were fixed, but not all. Please fix at least 2 of these design issues for this review to be approved.

**Review by selectthegang — APPROVED** [review]

**Comment by selectthegang** [comment]
I have approved this review as the code looks good and runs well!

**Review by Codemonkey51 — APPROVED** [review]
Just tested locally, LGTM!

**Pull request merged**
